# Generated by Django 4.0.2 on 2022-03-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_images_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(default='blog_app/image_for_blog.jpeg', upload_to='blog_app/static/blog_app'),
        ),
    ]
